CREATE TABLE cf_movie (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          title VARCHAR2(255),
                          description VARCHAR2(255),
                          release_date DATE,
                          average_rating NUMBER(4,2),
                          poster_url VARCHAR2(500),
                          CONSTRAINT pk_cf_movie PRIMARY KEY (id)
);

CREATE TABLE cf_movie_genres (
                                 movie_id NUMBER NOT NULL,
                                 genre VARCHAR2(255)
);

CREATE TABLE cf_movie_list (
                               id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               name VARCHAR2(255),
                               user_id NUMBER,
                               CONSTRAINT pk_cf_movie_list PRIMARY KEY (id)
);

CREATE TABLE cf_movie_list_movies (
                                      movie_id NUMBER NOT NULL,
                                      movie_list_id NUMBER NOT NULL
);

CREATE TABLE cf_review (
                           id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           user_id NUMBER,
                           movie_id NUMBER,
                           rating NUMBER(4,2),
                           comments VARCHAR2(255),
                           CONSTRAINT pk_cf_review PRIMARY KEY (id)
);

CREATE TABLE cf_user (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         name VARCHAR2(255),
                         email VARCHAR2(255),
                         password VARCHAR2(255),
                         age NUMBER(3),
                         is_admin NUMBER(1), -- Oracle não tem BOOLEAN
                         CONSTRAINT pk_cf_user PRIMARY KEY (id)
);

-- FKs

ALTER TABLE cf_movie_list
    ADD CONSTRAINT fk_cf_movie_list_user
        FOREIGN KEY (user_id) REFERENCES cf_user (id);

ALTER TABLE cf_review
    ADD CONSTRAINT fk_cf_review_movie
        FOREIGN KEY (movie_id) REFERENCES cf_movie (id);

ALTER TABLE cf_review
    ADD CONSTRAINT fk_cf_review_user
        FOREIGN KEY (user_id) REFERENCES cf_user (id);

ALTER TABLE cf_movie_genres
    ADD CONSTRAINT fk_cf_movie_genres_movie
        FOREIGN KEY (movie_id) REFERENCES cf_movie (id);

ALTER TABLE cf_movie_list_movies
    ADD CONSTRAINT fk_cf_movie_list_movies_movie
        FOREIGN KEY (movie_id) REFERENCES cf_movie (id);

ALTER TABLE cf_movie_list_movies
    ADD CONSTRAINT fk_cf_movie_list_movies_list
        FOREIGN KEY (movie_list_id) REFERENCES cf_movie_list (id);