CREATE TABLE cf_movie
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255),
    description    VARCHAR(255),
    release_date   date,
    average_rating DECIMAL(4,2),
    poster_url VARCHAR(500),
    CONSTRAINT pk_cf_movie PRIMARY KEY (id)
);

CREATE TABLE cf_movie_genres
(
    movie_id BIGINT NOT NULL,
    genre    VARCHAR(255)
);

CREATE TABLE cf_movie_list
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    user_id BIGINT,
    CONSTRAINT pk_cf_movie_list PRIMARY KEY (id)
);

CREATE TABLE cf_movie_list_movies
(
    movie_id      BIGINT NOT NULL,
    movie_list_id BIGINT NOT NULL
);

CREATE TABLE cf_review
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT,
    movie_id BIGINT,
    rating   DECIMAL(4,2),
    comments VARCHAR(255),
    CONSTRAINT pk_cf_review PRIMARY KEY (id)
);

CREATE TABLE cf_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    age      INT,
    is_admin BOOLEAN,
    CONSTRAINT pk_cf_user PRIMARY KEY (id)
);

ALTER TABLE cf_movie_list
    ADD CONSTRAINT FK_CF_MOVIE_LIST_ON_USER FOREIGN KEY (user_id) REFERENCES cf_user (id);

ALTER TABLE cf_review
    ADD CONSTRAINT FK_CF_REVIEW_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES cf_movie (id);

ALTER TABLE cf_review
    ADD CONSTRAINT FK_CF_REVIEW_ON_USER FOREIGN KEY (user_id) REFERENCES cf_user (id);

ALTER TABLE cf_movie_genres
    ADD CONSTRAINT fk_cf_movie_genres_on_movie FOREIGN KEY (movie_id) REFERENCES cf_movie (id);

ALTER TABLE cf_movie_list_movies
    ADD CONSTRAINT fk_cfmovlismov_on_movie FOREIGN KEY (movie_id) REFERENCES cf_movie (id);

ALTER TABLE cf_movie_list_movies
    ADD CONSTRAINT fk_cfmovlismov_on_movie_list FOREIGN KEY (movie_list_id) REFERENCES cf_movie_list (id);